### ISSUE TITLE
Go Semantic Completion installation failed on a Mac

### ISSUE THREAD

**Issue by indrayam** [zxqfl/tabnine-sublime#17]
My machine: MacBook Pro (MacOS Sierra 10.12.6)
Editor: Sublime Text (Version 3.1.1 Build 3176)
TabNine: Version 1.0.5
Other information: Paid License of TabNine

I tried to run `TabNine::sem`. It said that the Semantic Completion was enabled. However, when I started to type my Go code, it brought a message in the suggestions drop-down that the installation failed at running this command:

`go get -u github.com/sourcegraph/go-langserver`

I have manually run this command on my Mac and the thing installed without any errors. Not sure where to go look for errors.

Had to revert back by running `TabNine::no_sem`

**Comment by zxqfl** [comment]
Now that the language server is installed, what happens if you type TabNine::sem again?

**Comment by indrayam** [comment]
This is what happened.

Screenshot 1:
![Screenshot 1](https://s3.amazonaws.com/us-east-1-anand-files/go-semantic-completion-1.png)

Screenshot 2:
![Screenshot 2](https://s3.amazonaws.com/us-east-1-anand-files/go-semantic-completion-2.png)

Just so that I am clear, while I did install the Golang server  by running `go get -u github.com/sourcegraph/go-langserver`, I am not running this command in the background when I took the screenshot (`go-langserver -mode stdio -gocodecompletion`). I assumed that will be something TabNine will do behind the scenes.

**Comment by zxqfl** [comment]
Is go-langserver on your PATH?

**Comment by indrayam** [comment]
It is!
![Screenshot 3](https://s3.amazonaws.com/us-east-1-anand-files/go-semantic-completion-3.png)

**Comment by indrayam** [comment]
Yes! it works now! Is there a TabNine:: command to get a dump of the runtime configuration in effect.

Anyways, I think I am good for now! Thanks a bunch.

**Comment by zxqfl** [comment]
Great! There is no command, but the runtime configuration is given by `~/Library/Preferences/TabNine/ExampleTabNine.toml` plus whatever changes are in `~/Library/Preferences/TabNine/TabNine.toml`.
