### ISSUE TITLE
[request] make it possible to change the color of the popup

### ISSUE THREAD

**Issue by jabbalaci** [zxqfl/tabnine-sublime#24]
In Sublime Text I use a light background, that's my preference. The suggestions of TabNine also appear in a popup with light background, and when I edit for instance a normal text file that has no syntax highlighting, it's very hard to see and read the TabNine popup. Is there a way to change the colors of the popup?

**Comment by zxqfl** [comment]
Hi,

TabNine uses the popup functionality from Sublime Text's API, so you can change its colour by changing your theme. The relevant element is `popup_control html_popup` (https://www.sublimetext.com/docs/3/themes.html#elements). Note that TabNine does _not_ use the `auto_complete_popup` element.
