### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by axijia** [zxqfl/tabnine-sublime#26]
An error occurred while trying to unzip the package file for Tabnine . Please try installing the package again

**Comment by Freedomisgood** [comment]
[a problem when installing](https://github.com/zxqfl/tabnine-sublime/issues/28)
The same problem. Tackle it by downloading the code from github, then unzip..
But the effetion seems not good...I dont know whethere My settings is wrong.

**Comment by zxqfl** [comment]
I'm not sure what TabNine can do to fix this, since it isn't responsible for unzipping the package. I'm sorry for the trouble and I'm glad you found a workaround.
