### ISSUE TITLE
a problem when installing

### ISSUE THREAD

**Issue by adamchengdeng** [zxqfl/tabnine-sublime#28]
I can't finish the installation in sublime.It had a cue when installing that "an error occurred while trying to unzip the package file for TabNine.Please try installing the package again".I had tries several times,and already used another computer to install TabNine,but still that still did nothing.And now I had to believe it was the package that be wrong.

**Comment by zxqfl** [comment]
Can you install other packages from Package Control?

**Comment by adamchengdeng** [comment]
Thank you!!
Just now,I downloaded the zip on github.It works.
But I can't still found any other packages from Package Control.




------------------ 原始邮件 ------------------
发件人: "Jacob Jackson"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 上午9:07
收件人: "zxqfl/tabnine-sublime"<tabnine-sublime@noreply.github.com>;
抄送: "过去的都过去了"<910394034@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zxqfl/tabnine-sublime] a problem when installing (#28)




Can you install other packages from Package Control?
