### ISSUE TITLE
Some tips I can't understand what these mean

### ISSUE THREAD

**Issue by Antonio-hi** [zxqfl/tabnine-sublime#31]
When I type in the code Tabnine its works well, but I don't understand some of the message below the prompt.
`
Type TabNine::sem to enable semantic completion for Python.
This will run the flollowing commands:
pip install python-language-server
pyls
Type TabNine::no_sem  to suppress this message
To learn more.................
`
It seems that I haven't finished some settings, but I don't know how to solve this problem. And I don't know where I should type my pip instructions.
Could you give me some advice? 
Thank you.

**Comment by zxqfl** [comment]
You can type TabNine::sem and TabNine will run the commands for you. The message is just so that people know that TabNine is going to install something.
