### ISSUE TITLE
Deep TabNine (autocompletion with deep learning)

### ISSUE THREAD

**Issue by laukstein** [zxqfl/tabnine-sublime#33]
Does tabnine-sublime support [Deep TabNine](https://thenextweb.com/apps/2019/07/25/this-ai-powered-autocompleter-tool-can-speed-up-your-coding/) (autocompletion with deep learning)?
https://tabnine.com/blog/deep

**Comment by zxqfl** [comment]
Yep, you need a beta key but once you activate it it will work with any TabNine client.
