### ISSUE TITLE
Show percentage for auto suggestion

### ISSUE THREAD

**Issue by jasonycw** [zxqfl/tabnine-sublime#38]
From the blog post, the auto suggestion shows the percentage for the pop up after the `Tab`
![image](https://user-images.githubusercontent.com/4518597/62358480-65fe9780-b547-11e9-9629-f29e2e4e24b7.png)

But from my machine, the suggestion in C# files only shows `Tab`
![image](https://user-images.githubusercontent.com/4518597/62358569-8c243780-b547-11e9-8fb5-cfc201f23232.png)

Is there a setting to show that?

**Comment by zxqfl** [comment]
Are you using TabNine Cloud?

**Comment by jasonycw** [comment]
No, so only if I use TabNine Cloud I will get the %s, for the offline version, it will not have that?

**Comment by zxqfl** [comment]
You can also use TabNine Local to see the percentages (type `TabNine::config` to check that it is enabled).
