### ISSUE TITLE
Only works when "show_definitions" is true

### ISSUE THREAD

**Issue by lewisfff** [zxqfl/tabnine-sublime#7]
This isn't really a bug, but some users might think this plugin is broken if they have disabled the definition popup. 

It's one of the first things I disable in ST3 as it is a bit intrusive :-)

**Comment by zxqfl** [comment]
Thanks for the report, I'll add a popup message or something

**Comment by zxqfl** [comment]
Can you confirm that you tried it with `"show_definitions": false` and it didn't work? It still works for me when I set it to false.

**Comment by lewisfff** [comment]
You're right

Perhaps the act of restarting ST3 fixed it in this instance for me.
Likely a red herring.

Sorry for trouble :)
