### ISSUE TITLE
Cannot install due to invalid certificate

### ISSUE THREAD

**Issue by pedrorijo91** [zxqfl/tabnine-sublime#9]
When trying to install with the recommended steps:

* Install Package Control by pressing Ctrl+Shift+P (Cmd+Shift+P on OSX) and selecting Install Package Control.
* Install TabNine by pressing Ctrl+Shift+P (Cmd+Shift+P on OSX) and selecting Package Control: Install Package and then TabNine.

I get the following error:

```
ignored packages updated to: ["TabNine", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/zxqfl/tabnine-sublime/zip/0.2.2.
error: Package Control

Unable to download TabNine. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

```

**Comment by zxqfl** [comment]
Sorry, I could not reproduce this issue.

**Comment by pedrorijo91** [comment]
closed issue? it's an issue that's happening to someone trying to use your extension.

which sublime version are you using? v3.0 build 3143
which os version are you using? OS X 10.12.6

is there any more logs I can attach to debug this?

**Comment by zxqfl** [comment]
I do not know how to fix this issue. I think it is unlikely to be an issue with this extension because the issue occurred before the extension was downloaded.

**Comment by bohaohan** [comment]
Just update your Sublime
